# stage1 - build react app first 
FROM node:16.13.1-alpine3.14
# create the appropriate directories
ENV HOME=/home/app/holistiqumweb
ENV APP_HOME=/home/app/holistiqumweb
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ENV PATH  $APP_HOME/node_modules/.bin:$PATH

COPY . $APP_HOME

ARG REACT_APP_IS_PRODUCTION
ENV REACT_APP_IS_PRODUCTION=$REACT_APP_IS_PRODUCTION

RUN npm install
RUN npm run build


COPY . $APP_HOME
