name: Project_Test

on: [push]

jobs:

  Run_Tests:

    runs-on: ubuntu-latest
    env:
        ENVIROMENT: DEV
        SECRET_KEY: foo
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 0.0.0.0 192.168.1.82 [::1]
        SQL_ENGINE: django.db.backends.postgresql
        SQL_DATABASE: localholistiqumdb
        SQL_USER: localuser
        SQL_PASSWORD: localpassword
        SQL_HOST: db
        SQL_PORT: 5432
        DATABASE: postgres
        REDIS_HOST: redis
        SENDINBLUE_API_KEY: ""
        SLACK_TOKEN: ""
        API_PREFIX: "api"
        API_VERSION: "v1"
        API_URL: "api/v1/"
        STRIPE_FORWARD_URL: 192.168.0.4:8000/api/v1/payments/webhook/
        STRIPE_API_KEY: aa
        STRIPE_DEVICE_NAME: laptopjose
        STRIPE_ENDPOINT_SECRET: aa
        # GITHUB_WORKFLOW: True
        # MODE: workflow
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-python@v2 
    - name: Build the images and start the containers
      run: |
        touch .env.dev
        # export GITHUB_WORKFLOW=True
        # export MODE="Test"
        # docker-compose -f docker-compose.yml build
        # docker-compose -f docker-compose.yml up -d
        docker-compose up -d --build
        docker ps
    - name: Run django tests in container
      run: |
        docker ps
        docker exec api_test pytest -s 

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
