name: Project_Test

on: [push]

jobs:

  Run_Tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-python@v2 
    - name: Build the images and start the containers
      run: |
        touch .env.dev
        echo "${{ secrets }}" >> .env.dev
        cat .env.dev
        # export GITHUB_WORKFLOW=True
        # export MODE="Test"
        # docker-compose -f docker-compose.yml build
        # docker-compose -f docker-compose.yml up -d
        docker-compose up -d --build
        docker ps
    - name: Run django tests in container
      run: |
        docker ps
        docker exec api_test pytest -s 

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
