on: push
name: Runing all tests
jobs:
  run_tests: 
    runs-on: ubuntu_latest
    steps:
     - run: cd api # move to api folder
     - run: pip install -r requirements.txt # install all our dependencies for the project
     - run: docker-compse up -d 
     - run: docker exec api pytest -s 
